# Generated by Django 5.1.3 on 2024-12-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CCRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'CC Recipient',
                'verbose_name_plural': 'CC Recipients',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=32)),
                ('body', models.TextField(blank=True)),
                ('sender', models.EmailField(max_length=254)),
                ('recipient', models.EmailField(max_length=254)),
                ('attach', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('sent_at', models.DateField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending')),
                ('cc', models.ManyToManyField(blank=True, to='messaging.ccrecipient')),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
            },
        ),
    ]
