# Generated by Django 5.1.3 on 2024-12-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='cc',
        ),
        migrations.DeleteModel(
            name='CCRecipient',
        ),
        migrations.AddField(
            model_name='email',
            name='cc',
            field=models.JSONField(default=list),
        ),
    ]
